[ID1000702] implement blockchain adapter api
csiabb/blockchain-adapter pull request #10
Opened 2020-03-12 02:24 UTC by zhangbing16

--story=1000702 --user=zhangbing
https://www.tapd.cn/60210943/prong/stories/view/1160210943001000702

Signed-off-by: zhangbing <zhangbing@arxanchain.cm>

2020-03-12 02:38 UTC, genggjh requested changes
缺少必要的注释：

API应该增加必要的参数说明

UT测试应该增加测的是什么scenario

2020-03-12 02:38 UTC, hukunge submitted a review, later dismissed

2020-03-12 03:41 UTC, genggjh commented on controllers/blockchain/account_test.go
> +				Expect(resp.Code).Should(Equal(http.StatusBadRequest))
这里应该增加说明 这个测试是期望 没有提供哪些必要的参数，应该返回什么样的错误信息

2020-03-12 03:42 UTC, genggjh commented on controllers/blockchain/publicity_test.go
> +			It("missing required param", func() {
或者在这里说明白 missing 什么 param？

2020-03-13 02:25 UTC, genggjh approved these changes

2020-03-13 02:26 UTC, merged