[ID1000738] arxanchain blockchain callback
csiabb/blockchain-adapter pull request #12
Opened 2020-03-18 07:15 UTC by zhangbing16

--story=1000738 --user=zhangbing
https://www.tapd.cn/60210943/prong/stories/view/1160210943001000738

Signed-off-by: zhangbing <zhangbing@arxanchain.cm>

2020-03-18 07:32 UTC, genggjh approved these changes

2020-03-18 07:32 UTC, genggjh commented on components/callback/client.go
> +	PushTimeOut = time.Second * 5
这个应该放到配置文件里去

2020-03-18 07:32 UTC, genggjh commented on components/callback/client.go
> +	resp, err := c.pushClient.Post(url, "application/json;charset=utf-8", body)
这里是不是应该有个队列或者channel，否则并发消息多了会出问题的。
第一版可以先简单一些实现，然后加上todo，后续再优化。

2020-03-18 07:34 UTC, genggjh requested changes
应该再优化一下

2020-03-18 07:43 UTC, zhangbing16 commented on components/callback/client.go
> +	PushTimeOut = time.Second * 5
使用配置文件配置

2020-03-18 07:43 UTC, zhangbing16 commented on components/callback/client.go
> +	resp, err := c.pushClient.Post(url, "application/json;charset=utf-8", body)
第一版先简单实现，后续可以优化一下。

2020-03-18 07:46 UTC, genggjh commented on components/callback/client.go
> +	resp, err := c.pushClient.Post(url, "application/json;charset=utf-8", body)
但现在这种实现，会不会影响并发，有没有具体测试过？

2020-03-18 08:27 UTC, zhangbing16 commented on components/callback/client.go
> +	resp, err := c.pushClient.Post(url, "application/json;charset=utf-8", body)
第一阶段应该可以支持。

2020-03-18 08:39 UTC, genggjh commented on components/callback/client.go
> +	resp, err := c.pushClient.Post(url, "application/json;charset=utf-8", body)
那就应该加个TODO，写清楚后续需要加队列来优化

2020-03-18 08:44 UTC, zhangbing16 commented on components/callback/client.go
> +	resp, err := c.pushClient.Post(url, "application/json;charset=utf-8", body)
已经加上了

2020-03-19 02:42 UTC, genggjh approved these changes

2020-03-19 02:42 UTC, merged